kotlin.code.style=official
org.gradle.jvmargs=-Xmx4g -Dfile.encoding=UTF-8
kotlin.native.ignoreDisabledTargets=true
kotlin.mpp.enableCInteropCommonization=true

GROUP=dev.brahmkshatriya.wayland
VERSION_NAME=0.1.0-SNAPSHOT

POM_NAME=Wayland AppView
POM_DESCRIPTION=Embed Wayland-native Linux applications inside Compose Native UI.
POM_INCEPTION_YEAR=2026
POM_URL=https://github.com/brahmkshatriya/wayland-appview

POM_LICENCE_NAME=The Apache Software License, Version 2.0
POM_LICENCE_URL=https://www.apache.org/licenses/LICENSE-2.0.txt
POM_LICENCE_DIST=repo

POM_SCM_URL=https://github.com/brahmkshatriya/wayland-appview
POM_SCM_CONNECTION=scm:git:https://github.com/brahmkshatriya/wayland-appview.git
POM_SCM_DEV_CONNECTION=scm:git:git@github.com:brahmkshatriya/wayland-appview.git

POM_DEVELOPER_ID=brahmkshatriya
POM_DEVELOPER_NAME=Brahm Kshatriya
POM_DEVELOPER_URL=https://github.com/brahmkshatriya

SONATYPE_HOST=CENTRAL_PORTAL
RELEASE_SIGNING_ENABLED=true
SONATYPE_AUTOMATIC_RELEASE=true
